apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - git:
        repoURL: https://github.com/SmokersCough/k3s-argocd-starter.git
        revision: HEAD
        directories:
          - path: apps/monitoring/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        appset: monitoring
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: infrastructure
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/SmokersCough/k3s-argocd-starter.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        # Note: Automated sync is disabled to ensure networking apps complete first
        # Applications will be created but remain in "OutOfSync" until manually synced
        # or enabled via script/hook after networking apps (wave -1) are healthy
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
