apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  generators:
    # Storage first
    - git:
        repoURL: https://github.com/SmokersCough/k3s-argocd-starter.git
        revision: HEAD
        directories:
          - path: apps/infrastructure/storage/*

    # Controllers second
    - git:
        repoURL: https://github.com/SmokersCough/k3s-argocd-starter.git
        revision: HEAD
        directories:
          - path: apps/infrastructure/controllers/*

    # Networking third
    - git:
        repoURL: https://github.com/SmokersCough/k3s-argocd-starter.git
        revision: HEAD
        directories:
          - path: apps/infrastructure/networking/*

    # Monitoring next
    - git:
        repoURL: https://github.com/SmokersCough/k3s-argocd-starter.git
        revision: HEAD
        directories:
          - path: apps/monitoring/kube-prometheus-stack/*

    # Applications last
    - git:
        repoURL: https://github.com/SmokersCough/k3s-argocd-starter.git
        revision: HEAD
        directories:
          - path: apps/applications/*

  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        type: appset-manager
      annotations:
        # This assigns waves based on path patterns
        argocd.argoproj.io/sync-wave: |
          {{- if contains "storage" .path }}-3{{- else if contains "controllers" .path }}-2{{- else if contains "networking" .path }}-1{{- else if contains "monitoring" .path }}0{{- else }}1{{- end }}
    spec:
      project: infrastructure
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/SmokersCough/k3s-argocd-starter.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
