---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app: n8n
    component: secrets
stringData:
  # Database password
  DB_POSTGRESDB_PASSWORD: "L1ONzfNNKW14UxIbg0CoZ2l8y+xBe1yFS14IIFGcFBI="
  # Encryption key to hash all data
  N8N_ENCRYPTION_KEY: "b3ce6902ba3c84d095892b22b863381fea3ee83400fb6d8dfcbaddcb7a31a6d7"
