---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app: n8n
    component: secrets
stringData:
  # Database password
  DB_POSTGRESDB_PASSWORD: "tfNTEdYrSkzEsRV7Vfm80U5MafgStRcFgc6Aa1icruM="
  # Encryption key to hash all data
  N8N_ENCRYPTION_KEY: "5707aa0ea180c42c4fb3c0465c4f196db3b6d9cee15afae9677ce47fd886fa2c"
