---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app: n8n
    component: secrets
stringData:
  # Database password
  DB_POSTGRESDB_PASSWORD: "n8n"
  # Encryption key to hash all data (IMPORTANT: Change this in production!)
  N8N_ENCRYPTION_KEY: "n8n"
